---
name: GameModes
version: 0.0.2
main: Tatsomi\GameModes\Main
api: 5.0.0
src-namespace-prefix: Tatsomi\GameModes

commands:
  gms:
    permission: gms.cmd
    description: §bChange your gamemode to §3Survival
  gmc:
    permission: gmc.cmd
    description: §bChange your gamemode to §3Creative
  gmsp:
    permission: gmsp.cmd
    description: §bChange your gamemode to §3Spectator
  gma:
    permission: gma.cmd
    description: §bChange your gamemode to §3Adventure
  gmui:
    permission: gmui.cmd
    description: §bOpen GameModes §3Menu

permissions:
  gms.cmd:
    default: false
  gmc.cmd:
    default: false
  gmsp.cmd:
    default: false
  gma.cmd:
    default: false
  gmui.cmd:
    default: false
